# Use root/example as user/password credentials
version: '3'
services:
  vishva_database:
    image: mysql
    container_name: vishva_database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      # MYSQL_DATABASE: vany
      MYSQL_USER: vishva
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_HOST: '%'
    networks:
      - net
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - vishva_database
    image: phpmyadmin/phpmyadmin
    container_name: vishva_database_access
    restart: always
    ports:
      - '8080:80'
    links: 
      - vishva_database:vishva_database
    environment:
      PMA_HOST: vishva_database
      PMA_PORT: 3306
    networks:
      - net
networks:
  net: